version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      - FLASK_ENV=development
    expose:
      - "5000"
    volumes:
      - nfs_static:/app/static
    networks:
      - bookstore_net

volumes:
  db_data:
  nfs_static:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fs-0ab6ccd6c572caef0.efs.us-east-1.amazonaws.com,nfsvers=4.1,rw
      device: ":/static"

networks:
  bookstore_net:
