version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      - FLASK_ENV=development
    expose:
      - "5000"
    networks:
      - bookstore_net

volumes:
  db_data:

networks:
  bookstore_net:
